name: Export PR Comments

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  export-comments:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up GitHub CLI
        uses: cli/cli@v2

      - name: Export PR comments to Markdown
        run: |
          echo "# Release Notes for $GITHUB_REF_NAME" > release_notes.md
          PRS=$(gh pr list --state merged --base main --limit 20 --json number,title --jq '.[] | [.number, .title] | @tsv')
          while IFS=$'\t' read -r number title; do
            echo -e "\n## PR #$number - $title" >> release_notes.md
            gh pr view $number --json comments --jq '.comments[].body' >> release_notes.md || echo "No comments" >> release_notes.md
          done <<< "$PRS"

      - name: Upload release notes
        uses: actions/upload-artifact@v4
        with:
          name: release-notes
          path: release_notes.md
