name: Generate Release Notes

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        run: |
          sudo apt update
          sudo apt install python3 -y
          python3 --version
          sudo apt install python3-pip -y

      - name: Install dependencies
        run: pip install jinja2

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Generate release notes using Jinja template
        run: |
          python scripts/generate_release_notes.py

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Remove existing release_notes.md if present
        run: |
          rm -f release_notes.md

      - name: Ensure main branch is checked out
        run: |
          git fetch origin main
          git checkout main

      - name: Add and commit release notes
        run: |
          git add release_notes.md
          git commit -m "Add release notes for ${{ github.ref_name }}" || echo "No changes to commit"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main
